### PR TITLE
fix(deps): update kbackend

### PR DESCRIPTION
**Pull request by elhub-no**
This PR contains the following updates:

| Package | Change | [Age](https://docs.renovatebot.com/merge-confidence/) | [Confidence](https://docs.renovatebot.com/merge-confidence/) |
|---|---|---|---|
| [ch.qos.logback:logback-classic](http://logback.qos.ch) ([source](https://redirect.github.com/qos-ch/logback), [changelog](https://logback.qos.ch/news.html)) | `1.5.33` → `1.5.34` | age | confidence |
| [io.mockk:mockk](https://mockk.io) ([source](https://redirect.github.com/mockk/mockk)) | `1.14.9` → `1.14.11` | age | confidence |
| [io.micrometer:micrometer-registry-prometheus](https://redirect.github.com/micrometer-metrics/micrometer) | `1.16.5` → `1.17.0` | age | confidence |
| org.jetbrains.kotlin.plugin.serialization | `2.3.21` → `2.4.0` | age | confidence |
| [io.insert-koin.compiler.plugin](https://insert-koin.io/) ([source](https://redirect.github.com/InsertKoinIO/koin-compiler-plugin)) | `1.0.0` → `1.0.1` | age | confidence |
| no.elhub.devxp:devxp-json-api-wrapper | `0.4.17` → `0.5.0` | age | confidence |
| [com.sksamuel.cohort:cohort-micrometer](https://redirect.github.com/sksamuel/cohort) | `2.9.8` → `2.9.9` | age | confidence |
| [com.sksamuel.cohort:cohort-ktor](https://redirect.github.com/sksamuel/cohort) | `2.9.8` → `2.9.9` | age | confidence |
| [com.sksamuel.cohort:cohort-hikari](https://redirect.github.com/sksamuel/cohort) | `2.9.8` → `2.9.9` | age | confidence |
| [io.arrow-kt:arrow-fx-coroutines](https://arrow-kt.io/) ([source](https://redirect.github.com/arrow-kt/arrow)) | `2.2.2.1` → `2.2.3` | age | confidence |
| [io.arrow-kt:arrow-core](https://arrow-kt.io/) ([source](https://redirect.github.com/arrow-kt/arrow)) | `2.2.2.1` → `2.2.3` | age | confidence |

---

### Release Notes

<details>
<summary>mockk/mockk (io.mockk:mockk)</summary>

#### What's Changed

- fix: added SameInstanceMatcher to handle an issue with equals method when using EqMatcher along with a mock to an object by [@&#8203;DOssaA](https://redirect.github.com/DOssaA) in [#&#8203;1508](https://redirect.github.com/mockk/mockk/pull/1508)
- Add scoped confirmVerified overloads for callables (KFunction and KProperty) by [@&#8203;DOssaA](https://redirect.github.com/DOssaA) in [#&#8203;1513](https://redirect.github.com/mockk/mockk/pull/1513)
- feat: support MockKAnnotation.useDependencyOrder for JUnit 5 by [@&#8203;ilia1243](https://redirect.github.com/ilia1243) in [#&#8203;1515](https://redirect.github.com/mockk/mockk/pull/1515)
- Allow updating settings from code by [@&#8203;Yentis](https://redirect.github.com/Yentis) in [#&#8203;1517](https://redirect.github.com/mockk/mockk/pull/1517)
- Add currentThread filter and excluded mocks to clearAllStubsFromMemory by [@&#8203;evgenru](https://redirect.github.com/evgenru) in [#&#8203;1519](https://redirect.github.com/mockk/mockk/pull/1519)
- Support new Kotlin annotation defaulting rule for [@&#8203;InjectMockKs](https://redirect.github.com/InjectMockKs) by [@&#8203;ZzAve](https://redirect.github.com/ZzAve) in [#&#8203;1525](https://redirect.github.com/mockk/mockk/pull/1525)
- feat(dsl): Add context parameters support module ([#&#8203;1431](https://redirect.github.com/mockk/mockk/issues/1431)) by [@&#8203;faraz152](https://redirect.github.com/faraz152) in [#&#8203;1521](https://redirect.github.com/mockk/mockk/pull/1521)
- fix: resolve [@&#8203;InjectMockKs](https://redirect.github.com/InjectMockKs) dependency order for interface by [@&#8203;neungs-2](https://redirect.github.com/neungs-2) in [#&#8203;1526](https://redirect.github.com/mockk/mockk/pull/1526)
- fix: resolve [@&#8203;InjectMockKs](https://redirect.github.com/InjectMockKs) dependency order for list injection by [@&#8203;ilia1243](https://redirect.github.com/ilia1243) in [#&#8203;1527](https://redirect.github.com/mockk/mockk/pull/1527)
- fix: extract native lib from APK when not on filesystem (AGP 8.5+) by [@&#8203;snowykte0426](https://redirect.github.com/snowykte0426) in [#&#8203;1529](https://redirect.github.com/mockk/mockk/pull/1529)
- fix: support OpenJ9 in JvmAutoHinter by [@&#8203;hspedro](https://redirect.github.com/hspedro) in [#&#8203;1530](https://redirect.github.com/mockk/mockk/pull/1530)

#### New Contributors

- [@&#8203;DOssaA](https://redirect.github.com/DOssaA) made their first contribution in [#&#8203;1508](https://redirect.github.com/mockk/mockk/pull/1508)
- [@&#8203;ilia1243](https://redirect.github.com/ilia1243) made their first contribution in [#&#8203;1515](https://redirect.github.com/mockk/mockk/pull/1515)
- [@&#8203;Yentis](https://redirect.github.com/Yentis) made their first contribution in [#&#8203;1517](https://redirect.github.com/mockk/mockk/pull/1517)
- [@&#8203;evgenru](https://redirect.github.com/evgenru) made their first contribution in [#&#8203;1519](https://redirect.github.com/mockk/mockk/pull/1519)
- [@&#8203;ZzAve](https://redirect.github.com/ZzAve) made their first contribution in [#&#8203;1525](https://redirect.github.com/mockk/mockk/pull/1525)
- [@&#8203;faraz152](https://redirect.github.com/faraz152) made their first contribution in [#&#8203;1521](https://redirect.github.com/mockk/mockk/pull/1521)
- [@&#8203;hspedro](https://redirect.github.com/hspedro) made their first contribution in [#&#8203;1530](https://redirect.github.com/mockk/mockk/pull/1530)

**Full Changelog**: <https://github.com/mockk/mockk/compare/1.14.9...v1.14.11>

</details>

<details>
<summary>micrometer-metrics/micrometer (io.micrometer:micrometer-registry-prometheus)</summary>

### [`v1.17.0`](https://redirect.github.com/micrometer-metrics/micrometer/releases/tag/v1.17.0): 1.17.0

See also the [1.17 migration guide](https://redirect.github.com/micrometer-metrics/micrometer/wiki/1.17-Migration-Guide) and the release notes for [1.17.0-RC1](https://redirect.github.com/micrometer-metrics/micrometer/releases/tag/v1.17.0-RC1), [1.17.0-M3](https://redirect.github.com/micrometer-metrics/micrometer/releases/tag/v1.17.0-M3), [1.17.0-M2](https://redirect.github.com/micrometer-metrics/micrometer/releases/tag/v1.17.0-M2), [1.17.0-M1](https://redirect.github.com/micrometer-metrics/micrometer/releases/tag/v1.17.0-M1).

#### :lady\_beetle: Bug Fixes

- ArrayIndexOutOfBoundsException when using LongTaskTimer [#&#8203;3877](https://redirect.github.com/micrometer-metrics/micrometer/issues/3877)
- Jetty 12's TimedHandler marks some requests with outcome UNKNOWN [#&#8203;7276](https://redirect.github.com/micrometer-metrics/micrometer/issues/7276)
- MeterRegistry closes HighCardinalityTagsDetector twice if the registry is closed twice [#&#8203;7409](https://redirect.github.com/micrometer-metrics/micrometer/issues/7409)
- Reduce allocation in HTTP server instrumentation [#&#8203;7580](https://redirect.github.com/micrometer-metrics/micrometer/issues/7580)
- Reduce allocation in gRPC server convention [#&#8203;7581](https://redirect.github.com/micrometer-metrics/micrometer/issues/7581)

#### :notebook\_with\_decorative\_cover: Documentation

- Clarify time series produced by LongTaskTimer when using Prometheus [#&#8203;6507](https://redirect.github.com/micrometer-metrics/micrometer/issues/6507)
- Document metrics that need to close the MeterBinder [#&#8203;4624](https://redirect.github.com/micrometer-metrics/micrometer/issues/4624)
- Multigauge Documentation lacks overwrite=true [#&#8203;4403](https://redirect.github.com/micrometer-metrics/micrometer/issues/4403)

#### :hammer: Dependency Upgrades

- Bump com.dynatrace.metric.util:dynatrace-metric-utils-java from 2.4.0 to 2.5.0 [#&#8203;7452](https://redirect.github.com/micrometer-metrics/micrometer/pull/7452)
- Bump com.google.auth:google-auth-library-oauth2-http from 1.43.0 to 1.48.0 [#&#8203;7397](https://redirect.github.com/micrometer-metrics/micrometer/pull/7397)
- Bump com.google.cloud:google-cloud-monitoring from 3.89.0 to 3.94.0 [#&#8203;7398](https://redirect.github.com/micrometer-metrics/micrometer/pull/7398)
- Bump com.google.cloud:libraries-bom from 26.79.0 to 26.83.0 [#&#8203;7497](https://redirect.github.com/micrometer-metrics/micrometer/pull/7497)
- Bump com.netflix.spectator:spectator-reg-atlas from 1.9.6 to 1.9.9 [#&#8203;7552](https://redirect.github.com/micrometer-metrics/micrometer/pull/7552)
- Bump dropwizard-metrics from 4.2.38 to 4.2.39 [#&#8203;7527](https://redirect.github.com/micrometer-metrics/micrometer/pull/7527)
- Bump io.prometheus:prometheus-metrics-bom from 1.5.1 to 1.7.0 [#&#8203;7572](https://redirect.github.com/micrometer-metrics/micrometer/pull/7572)
- Bump software.amazon.awssdk:cloudwatch from 2.42.32 to 2.46.4 [#&#8203;7494](https://redirect.github.com/micrometer-metrics/micrometer/pull/7494)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;blaspat](https://redirect.github.com/blaspat), [@&#8203;codingkiddo](https://redirect.github.com/codingkiddo), [@&#8203;izeye](https://redirect.github.com/izeye), [@&#8203;jewoodev](https://redirect.github.com/jewoodev), and [@&#8203;schiemon](https://redirect.github.com/schiemon)

#### :lady\_beetle: Bug Fixes

- ArrayIndexOutOfBoundsException when using LongTaskTimer [#&#8203;3877](https://redirect.github.com/micrometer-metrics/micrometer/issues/3877)
- Jetty 12's TimedHandler marks some requests with outcome UNKNOWN [#&#8203;7276](https://redirect.github.com/micrometer-metrics/micrometer/issues/7276)
- MeterRegistry closes HighCardinalityTagsDetector twice if the registry is closed twice [#&#8203;7409](https://redirect.github.com/micrometer-metrics/micrometer/issues/7409)
- Reduce allocation in HTTP server instrumentation [#&#8203;7580](https://redirect.github.com/micrometer-metrics/micrometer/issues/7580)
- Reduce allocation in gRPC server convention [#&#8203;7581](https://redirect.github.com/micrometer-metrics/micrometer/issues/7581)

#### :notebook\_with\_decorative\_cover: Documentation

- Clarify time series produced by LongTaskTimer when using Prometheus [#&#8203;6507](https://redirect.github.com/micrometer-metrics/micrometer/issues/6507)
- Document metrics that need to close the MeterBinder [#&#8203;4624](https://redirect.github.com/micrometer-metrics/micrometer/issues/4624)
- Multigauge Documentation lacks overwrite=true [#&#8203;4403](https://redirect.github.com/micrometer-metrics/micrometer/issues/4403)

#### :hammer: Dependency Upgrades

- Bump com.netflix.spectator:spectator-reg-atlas from 1.9.6 to 1.9.9 [#&#8203;7552](https://redirect.github.com/micrometer-metrics/micrometer/pull/7552)
- Bump dropwizard-metrics from 4.2.38 to 4.2.39 [#&#8203;7527](https://redirect.github.com/micrometer-metrics/micrometer/pull/7527)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;blaspat](https://redirect.github.com/blaspat), [@&#8203;codingkiddo](https://redirect.github.com/codingkiddo), [@&#8203;izeye](https://redirect.github.com/izeye), [@&#8203;jewoodev](https://redirect.github.com/jewoodev), and [@&#8203;schiemon](https://redirect.github.com/schiemon)

</details>

<details>
<summary>InsertKoinIO/koin-compiler-plugin (io.insert-koin.compiler.plugin)</summary>

### [`v1.0.1`](https://redirect.github.com/InsertKoinIO/koin-compiler-plugin/releases/tag/1.0.1)

[Compare Source](https://redirect.github.com/InsertKoinIO/koin-compiler-plugin/compare/1.0.0...1.0.1)

A maintenance release focused on **Kotlin 2.4.0 support** and **Kotlin/Native + WASM/JS build reliability**. One plugin artifact now spans **Kotlin 2.3.20 → 2.4.x**.

#### 🔑 Highlights

- **Kotlin 2.4.0 support** — the plugin no longer crashes on Kotlin 2.4.0, and the same artifact also works on Kotlin 2.3.20.
- **iOS / Native / WASM builds fixed** — annotation definitions no longer break KLIB serialization.
- **`@Single(createdAtStart = true)` honored** on definition functions — eager singletons are created at `startKoin` again.

##### Kotlin version compatibility — [#&#8203;19](https://redirect.github.com/InsertKoinIO/koin-compiler-plugin/issues/19), [#&#8203;42](https://redirect.github.com/InsertKoinIO/koin-compiler-plugin/issues/42) (and [koin#2431](https://redirect.github.com/koin/koin-compiler-plugin/issues/2431))

The plugin hard-crashed on the two most recent Kotlin versions:

- **Kotlin 2.4.0** — `ClassCastException` during FIR extension registration.
- **Kotlin 2.3.20** — `NoSuchMethodError` (`IrDeclarationOrigin.IR_EXTERNAL_DECLARATION_STUB`).

1.0.1 introduces a **Kotlin version-adapter layer**: the core is compiled against the stable IR API, and a small per-version adapter (selected at compile time) absorbs the breaking compiler-internal differences. A single published jar supports **Kotlin 2.3.20 and 2.4.0**; an unrecognized newer Kotlin gets a warning and best-effort support, while versions below the floor get a clear, actionable error instead of an internal crash.

##### Duplicate `injectedparams_*` signatures broke iOS + WASM/JS — [#&#8203;44](https://redirect.github.com/InsertKoinIO/koin-compiler-plugin/issues/44), [#&#8203;40](https://redirect.github.com/InsertKoinIO/koin-compiler-plugin/issues/40)

A type collected by more than one `@ComponentScan` module generated the `@InjectedParam` hint function twice with identical signatures. The JVM tolerated it; KLIB serialization (iOS/Native/WASM/JS) rejected it with *"Different declarations with the same signatures"*. The hint is now emitted exactly once per target. **(Regression vs 1.0.0-RC2.)**

##### WASM/JS KLIB serialization — [#&#8203;40](https://redirect.github.com/InsertKoinIO/koin-compiler-plugin/issues/40)

The plugin's generated hint files lacked a resolvable source, failing the JS/WASM KLIB serializer (*"No file found for source null"*). Fixed — **DSL-based projects now build on WASM/JS**.

##### `@Single(createdAtStart = true)` silently dropped — [koin#2425](https://redirect.github.com/koin/koin-compiler-plugin/issues/2425), [koin#2415](https://redirect.github.com/koin/koin-compiler-plugin/issues/2415)

`createdAtStart = true` on a `@Single` / `@Singleton` **definition function** inside a `@Module` was discarded in codegen, so eager singletons were never created at `startKoin` (no error or warning). Now propagated correctly. (The `@Module(createdAtStart)` and `@Singleton class` cases were already fixed in 1.0.0-RC3.13.)

#### ⚠️ Known limitation — annotation-based WASM/JS on Kotlin 2.3.20

Annotation-based projects (`@Module` / `@ComponentScan`) targeting **WASM/JS** require **Kotlin 2.4.0**. On Kotlin 2.3.20 they hit an upstream Kotlin compiler bug — [KT-82395](https://youtrack.jetbrains.com/issue/KT-82395) — in the JS/WASM KLIB metadata serializer, which the plugin cannot work around. **Kotlin 2.4.0 resolves it.** (iOS/Native and DSL-based WASM/JS are unaffected and work on both Kotlin versions.)

#### ✅ Compatibility

|                       | Kotlin 2.3.20 | Kotlin 2.4.0 |
| --------------------- | ------------- | ------------ |
| JVM / Android         | ✅             | ✅            |
| iOS / Native          | ✅             | ✅            |
| WASM/JS — DSL         | ✅             | ✅            |
| WASM/JS — annotations | ⚠️ KT-82395   | ✅            |

#### 📦 Install

```kotlin
plugins {
    id("io.insert-koin.compiler.plugin") version "1.0.1"
}
```

**Full changelog:** <https://github.com/InsertKoinIO/koin-compiler-plugin/compare/1.0.0...1.0.1>

</details>

<details>
<summary>sksamuel/cohort (com.sksamuel.cohort:cohort-micrometer)</summary>

##### What's Changed

- Correct misleading Hikari testOnBorrow/testOnCreate in /datasources by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;231](https://redirect.github.com/sksamuel/cohort/pull/231)
- Convert DBCP timeouts from seconds to milliseconds by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;210](https://redirect.github.com/sksamuel/cohort/pull/210)
- Key CohortMetrics counter cache by MeterRegistry; snapshot tags by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;237](https://redirect.github.com/sksamuel/cohort/pull/237)
- Treat NaN rate as unhealthy in KafkaConsumerRecordsConsumedRate check by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;214](https://redirect.github.com/sksamuel/cohort/pull/214)
- Propagate Cancellation/Interrupt in jedis Redis health checks by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;257](https://redirect.github.com/sksamuel/cohort/pull/257)
- Fix KDoc typo 'get file system' in DiskSpaceHealthCheck.defaults by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;208](https://redirect.github.com/sksamuel/cohort/pull/208)
- Add missing override val name to StartedThreadsHealthCheck by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;217](https://redirect.github.com/sksamuel/cohort/pull/217)
- Compare DiskSpaceHealthCheck on raw percentage, not roundToInt by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;207](https://redirect.github.com/sksamuel/cohort/pull/207)
- Reject unknown log levels in LogbackManager.set by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;203](https://redirect.github.com/sksamuel/cohort/pull/203)
- Reject unknown log levels in Log4j2Manager.set by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;204](https://redirect.github.com/sksamuel/cohort/pull/204)
- Avoid full stack-trace dump in ThreadStateHealthCheck by [@&#8203;sksamuel](https://redirect.github.com/sksamuel) in [#&#8203;227](https://redirect.github.com/sksamuel/cohort/pull/227)

**Full Changelog**: <https://github.com/sksamuel/cohort/compare/v2.9.8...v2.9.9>

</details>

<details>
<summary>arrow-kt/arrow (io.arrow-kt:arrow-fx-coroutines)</summary>

### [`v2.2.3`](https://redirect.github.com/arrow-kt/arrow/releases/tag/2.2.3)

[Compare Source](https://redirect.github.com/arrow-kt/arrow/compare/2.2.2.1...2.2.3)

##### What's Changed

- `Every` optics for `Set` by [@&#8203;serras](https://redirect.github.com/serras) in [#&#8203;3899](https://redirect.github.com/arrow-kt/arrow/pull/3899)
- Use common atomics on non-JVM platforms by [@&#8203;serras](https://redirect.github.com/serras) in [#&#8203;3879](https://redirect.github.com/arrow-kt/arrow/pull/3879)
- Add holdsIn contracts by [@&#8203;kyay10](https://redirect.github.com/kyay10) in [#&#8203;3803](https://redirect.github.com/arrow-kt/arrow/pull/3803)
- Updates for Kotlin 2.4.0 by [@&#8203;serras](https://redirect.github.com/serras) in [#&#8203;3904](https://redirect.github.com/arrow-kt/arrow/pull/3904)
- Improvements to Jackson integration with non-empty collections by [@&#8203;serras](https://redirect.github.com/serras) in [#&#8203;3909](https://redirect.github.com/arrow-kt/arrow/pull/3909)
- Keep Jackson ABI intact by [@&#8203;serras](https://redirect.github.com/serras) in [#&#8203;3911](https://redirect.github.com/arrow-kt/arrow/pull/3911)

**Full Changelog**: <https://github.com/arrow-kt/arrow/compare/2.2.2.1...2.2.3>

</details>

---

### Configuration

📅 **Schedule**: (UTC)

- Branch creation
  - At any time (no schedule defined)
- Automerge
  - At any time (no schedule defined)

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://redirect.github.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://redirect.github.com/renovatebot/renovate).

### CODE REVIEW

**Comment by enzo-crance-statnett** [comment]
:warning: does not compile as of today

**Review by kenneth-strand-statnett — APPROVED** [review]
